#!/usr/bin/env bash
#script that display Best School 10x but the L9 display best school then Hi on a new line
n=0

while [ $n -lt 10 ]
do
    echo "Best School"
    n=$(( n+1 ))
if
    [ $n = 9 ]
then
    echo "Hi"
fi
done
